---
sidebar: sidebar 
permalink: ontap98fo_vmware_virtualization.html 
keywords: FlexGroup, VMware, vSphere, NFS, 9.8, Virtual Storage Console, SnapCenter, Storage Replication Adapter, vVols 
summary: 이 페이지에서는 VMware NFS 데이터 저장소로 FlexGroup 볼륨을 프로비저닝하는 작업을 비롯하여 VMware 가상화를 위한 ONTAP 9.8의 새로운 통합 및 지원에 대해 설명합니다. 또한 전체 ONTAP 클러스터의 성능을 제공하는 확장 가능한 단일 데이터 저장소를 통해 데이터 저장소 관리를 간소화합니다. 
---
= VMware 가상화
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


ONTAP 9.8의 VMware 통합 및 지원은 FlexGroup 데이터 저장소 지원을 비롯한 여러 가지 새로운 기능으로 인해 향상됩니다. ONTAP 9.8을 사용하면 FlexGroup 볼륨을 VMware NFS 데이터 저장소로 프로비저닝할 수 있으므로 전체 ONTAP 클러스터의 성능을 제공하는 확장 가능한 단일 데이터 저장소를 통해 데이터 저장소 관리를 간소화할 수 있습니다. 이러한 새로운 기능 중 다수는 VMware vSphere 9.8 릴리즈용 ONTAP 툴과 함께 제공됩니다.

이는 다음과 같은 사항이 적용됨을 의미합니다.

* 검증된 성능 및 배치
* interop 한정자
* VAAI 복사 오프로드가 향상되어 작업을 신속하게 수행하고 백그라운드에서 완료합니다
* FlexGroup 프로비저닝, 크기 조정 및 삭제, 개별 VM에 대한 QoS 설정, VM에 대한 성능 메트릭(지연 시간, IOPS, 처리량)을 표시하는 등 가상 스토리지 콘솔이 지원됩니다
* NetApp SnapCenter 기본 스토리지 백업 및 복구 지원
* 최대 64TB VMFS LUN 지원 NetApp All-SAN 어레이에서 128TB LUN/300TB FlexVol 볼륨을 지원하므로 VMware vSphere 9.8 릴리즈용 ONTAP 툴에서 가상 스토리지 콘솔을 사용하여 최대 64TB VMFS 데이터 저장소를 프로비저닝할 수 있습니다.
* 증가 https://www.vmware.com/in/products/site-recovery-manager.html["SRM(사이트 복구 관리자)"^] 확장: VMware vSphere 9.8 릴리즈용 ONTAP 툴의 스토리지 복제 어댑터는 최대 512개까지 지원되는 데이터 저장소 및 보호 그룹의 크기를 늘립니다.
* REST API를 사용한 VMware vSphere VVOL 파일 메트릭 VVOL 파일 메트릭에 대한 REST API 지원이 ONTAP 9.8에 추가되어 가상 스토리지 콘솔에서 대시보드 및 보고서에 VVOL에 대한 ONTAP 스토리지 성능 메트릭을 표시할 수 있습니다.
* https://docs.vmware.com/en/Site-Recovery-Manager/8.3/com.vmware.srm.admin.doc/GUID-5651B2B8-6410-48AE-8882-6D51C85AC201.html["SRA(Storage Replication Adapter)"^] SnapMirror Synchronous 지원
* 에 대한 지원 https://tanzu.vmware.com/tanzu["VMware Tanzu입니다"^] 스토리지
* 향상된 SAN VVOL 재조정 명령 및 스토리지 기능 프로필의 개선 기능을 비롯하여 VVOL에 대한 지원 개선 최신 VMware 가상화 지원에 대한 자세한 내용은 다음 리소스를 참조하십시오.
* https://soundcloud.com/techontap_podcast/episode-263-virtualization-in-ontap-fall-2020-update["Tech OnTap 팟캐스트 에피소드 263: ONTAP에서의 가상화 – 2020년 가을"^]
* https://www.netapp.com/us/media/tr-4597.pdf["TR-4597: ONTAP가 설치된 VMware vSphere"^]

